### ISSUE TITLE
/viewteam command

### ISSUE THREAD

**Issue by jere-mie** [WinHacks/2022-bot#12]
Shows the team name, team leader, and team members in a Discord embed. The team is inferred based on the team that the command user is currently a member of. If the user isn't a member of a team, an error is displayed.

**Comment by kilbouri** [comment]
Added.

<img src="https://user-images.githubusercontent.com/52428953/148694795-3971f10a-da66-4249-9079-585b2de1cc8d.png" width=40% height=40%>
