### ISSUE TITLE
Create Schema.md file for database schema.

### ISSUE THREAD

**Issue by jere-mie** [WinHacks/2022-bot#14]
I think it'd be a good idea if we created a file that explains the schema of the database. For SQL, this would be the tables and the different columns in each table. I'm not too sure what the MongoDB equivalent is (something like collections and documents?)

**Comment by kilbouri** [comment]
Resolved by [6b73122](https://github.com/WinHacks/2022-bot/commit/6b73122b8597ddf6cf2791dd3dc70ad4655bd693)
