### ISSUE TITLE
ticket commands

### ISSUE THREAD

**Issue by jere-mie** [WinHacks/2022-bot#2]
NOTE: If the team commands are working then this issue can be ignored. However, having a ticketing system would be good to have if we can't get team chats working. 

There are two ticket commands:

/ticket  
Creates a channel with only you and our mentors. This must be used in the #support channel (this channel name may change) Each hacker can only have one ticket open at a time.

/closeticket  
Closes the open ticket (can only be used in a ticket channel, can be used by anyone who has access to the ticket channel). Closing doesn't delete the channel, but instead adds it to a "ticket archive" category.

**Comment by kilbouri** [comment]
Made redundant by #18.  Team commands now fully implemented.
