### ISSUE TITLE
/socials command

### ISSUE THREAD

**Issue by jere-mie** [WinHacks/2022-bot#5]
Displays an embed with all of the WinHacks social media accounts.  

- https://twitter.com/WinHacksCA
- http://facebook.com/WinHacksCA
- https://www.linkedin.com/company/winhacks
- https://instagram.com/winhacksca

**Comment by kilbouri** [comment]
Done.

<img src="https://user-images.githubusercontent.com/52428953/148704961-5595835f-37ae-45c4-8f84-a4e5e0bfdbc8.png" width=40%>
