### ISSUE TITLE
/createteam command

### ISSUE THREAD

**Issue by jere-mie** [WinHacks/2022-bot#7]
Hackers create a team with up to four people. 
Team name is given as a parameter. 
Duplicate team names are not allowed. 
Each user can only create one team, and if they are already a member of a team then they cannot create a team.
A private text channel and voice channel are created when a team is created. Only team members, mentors, moderators, and admins can see team channels.

**Comment by kilbouri** [comment]
Mostly working. Still need to add categories. Right now, the team channels are created in the global category (no limit, as far as I know)

**Comment by kilbouri** [comment]
Roses are red
Violets are blue
MongoDB lied to me
But its OK because I fixed the problem
My sanity is running out
But its ok because its only gonna be easier from here
